[package]
name = "anylinuxfs"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
libc = "0.2.171"
wait-timeout = "0.2.1"
objc2-core-foundation = "0.3.0"
objc2-disk-arbitration = "0.3.0"
url = "2.5.4"
